# Site settings
title: Music City Stats
email: n.strayer@vanderbilt.edu
description: > # this means to ignore newlines until "baseurl:"
  A blog about biostatistics, data, and data science in the music city. Helmed by Nick Strayer and
  Lucy D’Agostino McGowan.
baseurl: "/musicCityStats" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
